import type { Project } from '@/types';

export const PROJECTS_DATA: Project[] = [
  {
    id: 'proj-1',
    title: 'Global Banking Security Overhaul',
    industry: 'Financial Services',
    challenge: 'Major international bank faced increasing sophisticated cyber threats and needed comprehensive security assessment across 50+ global branches.',
    solution: 'Deployed full-scale penetration testing, security audits, and implemented zero-trust architecture with continuous monitoring.',
    results: [
      'Identified and remediated 127 critical vulnerabilities',
      '99.99% uptime achieved post-implementation',
      'Zero security breaches in 18 months',
      'Successfully passed SOC 2 Type II audit',
    ],
    technologies: ['AWS', 'Azure AD', 'Firewall Management', 'SIEM', 'Zero Trust Architecture'],
    image: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'security-audit',
  },
  {
    id: 'proj-2',
    title: 'E-Commerce Platform Penetration Test',
    industry: 'E-Commerce',
    challenge: 'Leading e-commerce platform processing $500M annually needed thorough security testing before Black Friday sales.',
    solution: 'Conducted comprehensive penetration testing covering web applications, APIs, mobile apps, and payment systems.',
    results: [
      'Discovered 43 vulnerabilities before going live',
      'Prevented potential data breach affecting 2M customers',
      'Record-breaking sales with zero downtime',
      'PCI DSS Level 1 compliance achieved',
    ],
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe', 'AWS Lambda'],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'penetration-testing',
  },
  {
    id: 'proj-3',
    title: 'Healthcare Cloud Migration',
    industry: 'Healthcare',
    challenge: 'Regional hospital network needed to migrate sensitive patient data to cloud while maintaining HIPAA compliance.',
    solution: 'Designed secure cloud architecture with encryption, access controls, and implemented DevSecOps pipeline for continuous security.',
    results: [
      '100% HIPAA compliance maintained',
      '40% reduction in infrastructure costs',
      '3x improvement in system performance',
      'Automated security scanning integrated',
    ],
    technologies: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'CloudWatch'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'cloud-security',
  },
  {
    id: 'proj-4',
    title: 'Enterprise Network Segmentation',
    industry: 'Manufacturing',
    challenge: 'Global manufacturing company with outdated flat network architecture vulnerable to lateral movement attacks.',
    solution: 'Implemented network segmentation, next-gen firewalls, and intrusion prevention systems across 15 facilities worldwide.',
    results: [
      'Reduced attack surface by 75%',
      'Blocked 10,000+ malicious attempts monthly',
      'Improved network performance by 35%',
      'Real-time threat visibility achieved',
    ],
    technologies: ['Cisco ASA', 'Palo Alto Firewalls', 'Splunk', 'VPN', 'IDS/IPS'],
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'network-security',
  },
  {
    id: 'proj-5',
    title: 'Tech Startup Infrastructure',
    industry: 'Technology',
    challenge: 'Fast-growing SaaS startup needed scalable, secure infrastructure to support 10x growth projection.',
    solution: 'Built cloud-native infrastructure with auto-scaling, load balancing, disaster recovery, and comprehensive monitoring.',
    results: [
      'Scaled from 10K to 100K users seamlessly',
      'Achieved 99.95% uptime SLA',
      'Automated deployment reduced release time by 80%',
      'Infrastructure costs optimized by 30%',
    ],
    technologies: ['GCP', 'Kubernetes', 'Terraform', 'PostgreSQL', 'Redis', 'Grafana'],
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'it-infrastructure',
  },
  {
    id: 'proj-6',
    title: 'Government Agency Security Audit',
    industry: 'Government',
    challenge: 'Federal agency required comprehensive security audit and compliance validation for critical infrastructure.',
    solution: 'Performed detailed security audit, vulnerability assessment, and provided strategic roadmap for security improvements.',
    results: [
      'Achieved FedRAMP authorization',
      'Remediated all high-severity findings',
      'Established continuous compliance monitoring',
      'Enhanced incident response capabilities',
    ],
    technologies: ['Tenable Nessus', 'Qualys', 'CIS Benchmarks', 'NIST Framework'],
    image: 'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?auto=format&fit=crop&q=80&w=800&fm=webp',
    category: 'security-audit',
  },
];
