import type { Service } from '@/types';
import { ServiceId } from './constants';

export const SERVICES_DATA: Service[] = [
  {
    id: ServiceId.PENETRATION_TESTING,
    title: 'Penetration Testing',
    description: 'Comprehensive ethical hacking services to identify and exploit vulnerabilities before malicious actors do. Our expert offensive security team simulates real-world sophisticated cyber attacks to stress-test your defenses, uncover hidden physical and digital flaws, and provide actionable remediation strategies to secure your critical assets.',
    icon: 'Shield',
    features: [
      'External & Internal Network Penetration Testing',
      'Web Application & API Security Assessment',
      'Mobile Application (iOS/Android) Testing',
      'Social Engineering & Phishing Simulations',
      'Red Team Operations & Physical Security Testing',
      'IoT & Embedded Device Security Assessments',
      'Zero-Day Vulnerability Research',
      'Detailed Remediation Reports & Debriefing',
    ],
    color: 'primary',
  },
  {
    id: ServiceId.SECURITY_AUDIT,
    title: 'Security Audit',
    description: 'Thorough evaluation of your entire security posture, organizational policies, and compliance status. We ensure your organization meets stringent global industry standards, aligns with best practices, and minimizes legal and financial risks associated with non-compliance and data breaches.',
    icon: 'FileSearch',
    features: [
      'Comprehensive Compliance Assessment (ISO 27001, SOC 2, PCI-DSS, GDPR)',
      'Information Security Policy Review & Development',
      'Identity & Access Management (IAM) Audits',
      'Cloud & On-Premise Configuration Reviews',
      'Third-Party & Supply Chain Risk Assessment',
      'Data Privacy & Protection Impact Analysis',
      'Incident Response Plan Evaluation',
      'Strategic Gap Analysis & Executive Reporting',
    ],
    color: 'secondary',
  },
  {
    id: ServiceId.NETWORK_SECURITY,
    title: 'Network Security',
    description: 'Advanced, multi-layered network protection solutions designed to safeguard your enterprise infrastructure from unauthorized access, sophisticated cyber attacks, malware, and catastrophic data breaches. We secure your perimeter and internal traffic flows.',
    icon: 'Network',
    features: [
      'Next-Gen Firewall (NGFW) Configuration & Management',
      'Intrusion Detection & Prevention Systems (IDS/IPS)',
      'Zero Trust Network Access (ZTNA) & Secure VPNs',
      'Micro-segmentation & Network Architecture Review',
      'Automated DDoS Protection & Mitigation',
      'Endpoint Detection & Response (EDR) Integration',
      'Wireless Network (Wi-Fi) Security Optimization',
      '24/7/365 Real-time Network Monitoring & Alerting',
    ],
    color: 'accent',
  },
  {
    id: ServiceId.CLOUD_SECURITY,
    title: 'Cloud Monitoring & Observability',
    description: 'Gain absolute visibility and granular control over your hybrid and multi-cloud environments. We provide comprehensive, real-time monitoring, intelligent logging, and deep observability solutions across AWS, Azure, Google Cloud, and Kubernetes clusters.',
    icon: 'Activity',
    features: [
      'Real-time Multi-Cloud Infrastructure Monitoring (AWS/Azure/GCP)',
      'Deep Application Performance Monitoring (APM)',
      'Centralized Log Management (SIEM) & Analytics',
      'Container & Kubernetes Security Posture Management (KSPM)',
      'Custom KPI Metrics & Executive Dashboards',
      'AI-driven Intelligent Alerting & Anomaly Detection',
      'Distributed Tracing & Rapid Root-Cause Debugging',
      'Cloud Cost Optimization & Traffic Analysis',
    ],
    color: 'primary',
  },
  {
    id: ServiceId.IT_INFRASTRUCTURE,
    title: 'IT Infrastructure',
    description: 'Architect, implement, and maintain robust, scalable, and highly resilient IT infrastructure. We deliver enterprise-grade reliability, uncompromised security, and peak performance to support your most demanding mission-critical business operations.',
    icon: 'Server',
    features: [
      'High-Availability Infrastructure Design & Implementation',
      'Modern Data Center & Server Management',
      'Disaster Recovery (DRaaS) & Business Continuity Planning',
      'Enterprise System Integration & Migration Services',
      'Hardware & Software Performance Optimization',
      'DevSecOps & Infrastructure as Code (IaC) (Terraform/Ansible)',
      'Virtualization & Hyperconverged Infrastructure (HCI)',
      '24/7 Infrastructure Support & Proactive Maintenance',
    ],
    color: 'secondary',
  },
  {
    id: ServiceId.MANAGED_SECURITY,
    title: 'Managed Security',
    description: 'Fully managed 24/7 Security Operations Center (SOC) services that continuously monitor, detect, and respond to threats across your entire digital environment. Our expert analysts and automated systems work around the clock to protect your business from evolving cyber threats.',
    icon: 'ShieldCheck',
    features: [
      '24/7 Security Operations Center (SOC) Monitoring',
      'Real-Time Threat Detection & Incident Response',
      'SIEM Management & Log Analysis',
      'Threat Intelligence & Proactive Hunting',
      'Vulnerability Management & Patch Coordination',
      'Security Awareness Training & Phishing Simulations',
      'Compliance Reporting & Executive Dashboards',
      'SLA-Backed Response Times & Dedicated Support',
    ],
    color: 'primary',
  },
];
